package:
  name: gsl
  version: 1.16

source:
  fn: gsl-1.16.tar.gz
  url: http://ftp.gnu.org/gnu/gsl/gsl-1.16.tar.gz
  md5: e49a664db13d81c968415cd53f62bc8b

build:
  number: 0

requirements:
  build:
    - python

about:
  home: http://www.gnu.org/software/gsl/
  license: GPL

